/**
 * Tests for the enhanced GitHub issues module.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  formatIssueBody,
  isGhAvailable,
  isGhAuthenticated,
  fetchExistingIssueTitles,
} from '../../src/phases/github-issues';

describe('GitHub Issues', () => {
  describe('formatIssueBody', () => {
    it('formats a minimal finding', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Button does not work',
        severity: 'P1',
        category: 'functionality',
      });

      expect(body).toContain('## Button does not work');
      expect(body).toContain('P1');
      expect(body).toContain('functionality');
      expect(body).toContain('Generated by Project Completion Agent');
    });

    it('includes severity badge', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Critical bug',
        severity: 'P0',
        category: 'security',
      });

      expect(body).toContain('![P0]');
      expect(body).toContain('Critical');
    });

    it('includes PRD reference', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Missing feature',
        severity: 'P2',
        category: 'prd-gap',
        prd_section: '2.1',
        prd_requirement: 'Must display user avatar',
      });

      expect(body).toContain('### PRD Reference');
      expect(body).toContain('**Section:** 2.1');
      expect(body).toContain('**Requirement:** Must display user avatar');
    });

    it('includes steps to reproduce', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Form error',
        severity: 'P1',
        category: 'functionality',
        steps_to_reproduce: [
          'Navigate to /settings',
          'Click "Save" without filling fields',
          'Observe no validation error',
        ],
      });

      expect(body).toContain('### Steps to Reproduce');
      expect(body).toContain('1. Navigate to /settings');
      expect(body).toContain('2. Click "Save"');
      expect(body).toContain('3. Observe no validation error');
    });

    it('includes expected and actual behavior', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Wrong output',
        severity: 'P2',
        category: 'functionality',
        expected_behavior: 'Should show success message',
        actual_behavior: 'Shows error 500',
      });

      expect(body).toContain('### Expected Behavior');
      expect(body).toContain('Should show success message');
      expect(body).toContain('### Actual Behavior');
      expect(body).toContain('Shows error 500');
    });

    it('includes evidence section', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Console errors',
        severity: 'P1',
        category: 'quality',
        evidence: {
          screenshots: ['screenshot-001.png'],
          console_errors: ['TypeError: undefined is not a function'],
          network_requests: ['POST /api/data 500'],
        },
      });

      expect(body).toContain('### Evidence');
      expect(body).toContain('**Console Errors:**');
      expect(body).toContain('TypeError: undefined is not a function');
      expect(body).toContain('**Network Requests:**');
      expect(body).toContain('POST /api/data 500');
      expect(body).toContain('**Screenshots:**');
      expect(body).toContain('screenshot-001.png');
    });

    it('includes fix suggestion', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Missing null check',
        severity: 'P2',
        category: 'quality',
        fix_suggestion: 'Add null check before accessing user.name',
      });

      expect(body).toContain('### Suggested Fix');
      expect(body).toContain('Add null check before accessing user.name');
    });

    it('includes location info', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Bug in component',
        severity: 'P1',
        category: 'functionality',
        location: {
          url: 'https://example.com/dashboard',
          file: 'src/components/Dashboard.tsx',
          line: 42,
        },
      });

      expect(body).toContain('https://example.com/dashboard');
      expect(body).toContain('`src/components/Dashboard.tsx:42`');
    });

    it('includes confidence and component', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Layout issue',
        severity: 'P3',
        category: 'ui',
        confidence: 85,
        component: 'Header',
      });

      expect(body).toContain('85/100');
      expect(body).toContain('Header');
    });

    it('handles finding with all optional fields empty', () => {
      const body = formatIssueBody({
        id: 'F-001',
        title: 'Minimal finding',
        severity: 'P4',
        category: 'uncategorized',
      });

      expect(body).toContain('## Minimal finding');
      // Should NOT contain sections for empty fields
      expect(body).not.toContain('### Steps to Reproduce');
      expect(body).not.toContain('### Expected Behavior');
      expect(body).not.toContain('### Evidence');
      expect(body).not.toContain('### Suggested Fix');
    });
  });
});
